### PR TITLE
Resolve #16

### LINKED ISSUE #16: Remove first and last char from string - 8th kyu
https://www.codewars.com/kata/56bc28ad5bdaeb48760009b0/haskell

### PR DESCRIPTION
**Pull request by pbv2**
#16 Remove first and last char from string - 8th kyu

### CODE REVIEW

**Review by JonasJore — APPROVED** [review]
Looks good! ☕  have an approve! ✅

**Comment by JonasJore** [comment]
@pbv2 You can merge this PR into `master` whenever you want really 💯

**Comment by pbv2** [comment]
Sorry! I thought I had already merged. but now i don't know how to do it, can you teach me?

**Comment by JonasJore** [comment]
You should be able to see the button that says `Merge pull request` in this PR. Press that button 😄 
bilde

**Comment by pbv2** [comment]
weird, doesn't appear to me
image

**Comment by JonasJore** [comment]
hm thats weird. Maybe i have that option not available to contributors..

**Pull request merged**
